name: Assemble debug APK

on:
  push:
    branches: [ meow/* ]
  pull_request:
    branches: [ meow/main ]

jobs:
  build_debug_apk:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: APK build action
      uses: MayMeow/apk-build-action@v3
      with:
        android-compile-sdk: "30"
        android-build-tools: "30.0.2"
        android-sdk-tools: "6514223"
